"""Export modules for fabrication, assembly, and interoperability."""

from .capabilities import (
    CAPABILITY_MATRIX,
    ExportArtifactLog,
    ExportBackend,
    ExportCapability,
    ExportFormat,
    ExportSupport,
    ManufacturingExportLog,
    UnsupportedExportError,
    build_export_artifact_log,
    build_export_log,
    export_capability_matrix,
    get_export_capability,
    require_export_capability,
)
from .dsn import export_dsn
from .evidence import (
    DirectoryManufacturingEvidenceAdapter,
    ManufacturingArtifactEvidence,
    ManufacturingArtifactKind,
    ManufacturingEvidenceBundle,
    ManufacturingValidationEvidence,
    ManufacturingValidationStatus,
    collect_manufacturing_evidence,
)
from .ipc2581 import FabCapabilityDb, PanelLayout, compute_panel, export_ipc2581
from .ipcd356 import (
    IpcD356ParityReport,
    compare_ir_to_ipcd356,
    compare_ir_to_ipcd356_file,
    design_ref_net_map,
    generate_ipcd356,
    parse_ipcd356,
    write_ipcd356,
    write_ipcd356_parity_report,
)

__all__ = [
    "CAPABILITY_MATRIX",
    "DirectoryManufacturingEvidenceAdapter",
    "ExportArtifactLog",
    "ExportBackend",
    "ExportCapability",
    "ExportFormat",
    "ExportSupport",
    "FabCapabilityDb",
    "IpcD356ParityReport",
    "ManufacturingArtifactEvidence",
    "ManufacturingArtifactKind",
    "ManufacturingEvidenceBundle",
    "ManufacturingExportLog",
    "ManufacturingValidationEvidence",
    "ManufacturingValidationStatus",
    "PanelLayout",
    "UnsupportedExportError",
    "build_export_artifact_log",
    "build_export_log",
    "collect_manufacturing_evidence",
    "compare_ir_to_ipcd356",
    "compare_ir_to_ipcd356_file",
    "compute_panel",
    "design_ref_net_map",
    "export_capability_matrix",
    "export_dsn",
    "export_ipc2581",
    "generate_ipcd356",
    "get_export_capability",
    "parse_ipcd356",
    "require_export_capability",
    "write_ipcd356",
    "write_ipcd356_parity_report",
]
